name: Publish
run-name: Publish (${{ inputs.extension }})

on:
  workflow_call:
    inputs:
      extension:
        required: true
        type: string
    secrets:
      raycast-organization-token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extensions/${{ inputs.extension }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
      # TODO: cache npm
      - run: npm ci
      - run: npm run publish
        env:
          RAY_TOKEN: ${{ secrets.raycast-organization-token }}
